version: "1"

services:
  drupal:
    image: drupal
    ports:
      - "8080:80"
    volumes:
      - drupal—modules:/var/www/html/modules
      - drupal—sites:/var/mqw/html/sites
      - drupal-themes:/var/www/html/themes
      - drupa-profites:/var/www/html/profites
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mypsssd

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
